### PR TITLE
alert duration 0 note

### PR DESCRIPTION
**Pull request by iCollin**
add note that the HMI should assign a duration when the parameter is omitted or zero

todo:

- [x] add to subtle alert

### CODE REVIEW

**Comment by JackLivio** [comment]
Is there a suggetion for what the timeout should be? The behavior in core seems intentional to allow the alert to be dismissed by the softbutton action, not by a timeout. I think the documentation should note that this is optional?

Also add punctuation please :)

**Comment by iCollin** [comment]
> Is there a suggetion for what the HMI Assigned timeout should be? The behavior in core seems intentional to allow the alert to be dismissed by the softbutton action, not by a timeout. I think the documentation should note that this is optional?

I remember the reason for this PR being that we wanted to make it clear that it is not optional to add a timeout - an HMI must add some timeout. Unfortunately I cannot remember exactly why, but we discussed this around the implementation of SubtleAlert last summer. One reason I can think of now is the possibility of leaking subscriptions/handlers in Core when a response does not arrive for a very long time. Also a persisting Alert can be annoying to the user, imagine if they are using navigation on the main screen and an alert is displayed, should they be forced to pay attention to the screen to see their maps again? I think a timeout is necessary.

Currently the SDL HMI applies a 30 second timeout to normal Alerts with soft buttons, but in all other cases Alerts are assigned a 10 second timeout. I do think it should be left up to the HMI how long the options will be presented. What do you think about just leaving a note in the documentation suggesting a timeout within the range of 10-60 seconds?

> Also add punctuation please :)

Added in https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/commit/5adc88bbf1f3ccd7bff389fa4e81de8cd8d8803e

**Comment by JackLivio** [comment]
Ok I would add a note that recommends a longer than usual timeout for alerts that contain soft buttons. Maybe this is something we look at changing in Core as well. I agree that it is probably not safe to have an indefinite alert on screen requiring user action.

**Comment by iCollin** [comment]
> Maybe this is something we look at changing in Core as well.

I agree completely, perhaps setting a timer to 75s or similar would be better than setting no timer at all.

In https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/pull/221/commits/66779b80a30e29985f42ee4cbdd6d37a8f83e16d I added a note that the timeout for alerts with soft buttons should be longer than usual.

**Review by JackLivio — APPROVED** [review]

**Pull request merged**
