### PR TITLE
sdl_rc_ capabilities

### PR DESCRIPTION
**Pull request by OlesiaV**
HMI integration guidelines for RC.IsReady and RC.GetCapabilities

### CODE REVIEW

**Comment by yang1070** [comment]
looks good to me

**Comment by yang1070** [comment]
there shall be a separate PR that add remoteControlCapability to SystemCapability

**Comment by JackLivio** [comment]
@OlesiaV @LuxoftAKutsan Please add new files to config.json so the new pages can be navigated to on developer portal

**Comment by LuxoftAKutsan** [comment]
@JackLivio @yang1070 I merged this changes to sdl_rc_baseline,
And it is available in PR https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/pull/69

**Pull request closed without merging**
