### PR TITLE
Add zh-cn indexs for [Getting Started, Overview, WebSocket Transport]

### PR DESCRIPTION
**Pull request by yifili09**
💥 Ready For Merge💥

### Summary
The purpose is to localize the portal for Chinese developers or potential local partners. That's a very first beginning to the translation work.

### TODO
- [x] Add **~/docs/Overview/index_zh-cn.md**
- [x] Add **~/docs/Getting Started/index_zh-cn.md**
- [x] Add **~/docs/WebSocket Transport/index_zh-cn.md**

### CODE REVIEW

**Comment by justinjdickow** [comment]
Preview this pull request at https://sdl.mobelux.com/docs/pull_request/d658289f1bda1ab3db037ecde76ebdf81dad97d6/

**Comment by yifili09** [comment]
@justinjdickow 

Any thoughts on the preview failure?

**Comment by justinjdickow** [comment]
Preview this pull request at http://127.0.0.1:8000/docs/pull_request/d658289f1bda1ab3db037ecde76ebdf81dad97d6/

**Comment by jemerick** [comment]
Sorry, that was me testing and building this PR locally.  Will have a fix out shortly.

**Comment by justinjdickow** [comment]
Preview this pull request at http://127.0.0.1:8000/docs/pull_request/d658289f1bda1ab3db037ecde76ebdf81dad97d6/

**Comment by justinjdickow** [comment]
Preview this pull request at http://127.0.0.1:8000/docs/pull_request/d658289f1bda1ab3db037ecde76ebdf81dad97d6/

Error - Traceback (most recent call last):
  File &quot;/Users/jason/development/python/livio-web/docs/tasks.py&quot;, line 469, in build_docdown_docs
    BuildLang.objects.bulk_create([BuildLang(build=build, lang=lang) for lang in languages])
NameError: global name &#39;BuildLang&#39; is not defined

**Comment by justinjdickow** [comment]
Preview this pull request at http://127.0.0.1:8000/docs/pull_request/d658289f1bda1ab3db037ecde76ebdf81dad97d6/

**Comment by jemerick** [comment]
Sorry for all of the comment spam... Try this:

https://sdl.mobelux.com/docs/zh-cn/pull_request/d658289f1bda1ab3db037ecde76ebdf81dad97d6/overview/

**Comment by justinjdickow** [comment]
Preview this pull request at https://sdl.mobelux.com/docs/pull_request/5bbfa90e4352365e66953e64f73f5fad62886379/overview/

**Comment by justinjdickow** [comment]
Here's the url that actually works haha https://sdl.mobelux.com/docs/zh-cn/pull_request/5bbfa90e4352365e66953e64f73f5fad62886379/overview/ @yifili09

**Comment by justinjdickow** [comment]
Preview this pull request at https://sdl.mobelux.com/docs/pull_request/3808cd6134e700cae14f086f6d26c80ff3119c44/overview/

**Comment by yifili09** [comment]
@justinjdickow @jemerick  

Thanks for the updating.  The automatic previewing system works fine other than the part of link **"/zh-cn/"** missing in the middle of **/docs/** and **/pull_request/**.  😂 😂 

Another glitch is about the markdown Head tag failed parsing for the first line whatever adding "space" or other stuffs. 

image

**Comment by justinjdickow** [comment]
Preview this pull request at http://127.0.0.1:8000/docs/pull_request/3808cd6134e700cae14f086f6d26c80ff3119c44/overview/

**Comment by justinjdickow** [comment]
Preview this pull request at http://127.0.0.1:8000/docs/pull_request/3808cd6134e700cae14f086f6d26c80ff3119c44/overview/

**Comment by justinjdickow** [comment]
Preview this pull request at http://127.0.0.1:8000/en-us/docs/pull_request/3808cd6134e700cae14f086f6d26c80ff3119c44/overview/

Error - Traceback (most recent call last):
  File &quot;/Users/jason/development/python/livio-web/docs/tasks.py&quot;, line 537, in build_docdown_docs
    output_format=&#39;html5&#39;
  File &quot;/Users/jason/.pyenv/versions/livio/lib/python2.7/site-packages/markdown/__init__.py&quot;, line 494, in markdown
    return md.convert(text)
  File &quot;/Users/jason/.pyenv/versions/livio/lib/python2.7/site-packages/markdown/__init__.py&quot;, line 375, in convert
    newRoot = treeprocessor.run(root)
  File &quot;/Users/jason/.pyenv/versions/livio/lib/python2.7/site-packages/markdown/treeprocessors.py&quot;, line 295, in run
    self.__handleInline(text), child
  File &quot;/Users/jason/.pyenv/versions/livio/lib/python2.7/site-packages/markdown/treeprocessors.py&quot;, line 106, in __handleInline
    data, patternIndex, startIndex)
  File &quot;/Users/jason/.pyenv/versions/livio/lib/python2.7/site-packages/markdown/treeprocessors.py&quot;, line 239, in __applyPattern
    node = pattern.handleMatch(match)
  File &quot;/Users/jason/.pyenv/versions/livio/lib/python2.7/site-packages/markdown/inlinepatterns.py&quot;, line 365, in handleMatch
    el.set(&quot;href&quot;, self.sanitize_url(self.unescape(href.strip())))
  File &quot;/Users/jason/development/python/livio-web/mxmarkdown/links.py&quot;, line 27, in sanitize_url
    activate(lang)
NameError: global name &#39;lang&#39; is not defined

**Comment by jemerick** [comment]
Sorry again for the comment spam.  I have updated our language support to use ISO 639-1 language codes, so `zh-hans` instead of `zh-cn` https://en.wikipedia.org/wiki/ISO_639_macrolanguage#zho

Can you update the markdown files from `index_zh-cn.md` to `index_zh-hans.md`?  Also update the language in the `config.json` file.

I have also fixed the first heading issue. There was an encoding issue when reading the files in to be parsed by markdown.

Also there is support for translating the navigation in the `config.json` if you wish to. Example (translations are from Google Translate, sorry if incorrect):

``` json
{
    "languages": ["en","zh-hans"],
    "navigation": [
        {
            "name": "Overview",
            "name_zh-hans": "概观"
        },
        {
          "name": "Getting Started",
          "name_zh-hans": "入门"
        },
        {
            "name": "WebSocket Transport",
            "name_zh-hans": "WebSocket的运输"
        }
    ]
}
```

Also, the language code is now utilized before the `/docs/` in the url like`https://sdl.mobelux.com/en/docs/HMI/master/overview/`

If you were to go to just `https://sdl.mobelux.com/docs/HMI/master/overview/` with no language code, it will attempt to direct you to the language code your browser sends in the accept language header. Once in a language, the navigation should remain in that language and not jump back to english (if there is a translated version available).

**Comment by justinjdickow** [comment]
Preview this pull request at https://smartdevicelink.com/docs/pull_request/f88a85d34206a54d9978ea80702488aad77be34e/overview/

**Comment by justinjdickow** [comment]
Preview this pull request at https://smartdevicelink.com/docs/pull_request/14d995af94537e8c6c36beaebc717c829e5edef6/overview/

Error - Traceback (most recent call last):
  File &quot;/var/django/livio/docs/tasks.py&quot;, line 469, in build_docdown_docs
    BuildLang.objects.bulk_create([BuildLang(build=build, lang=lang) for lang in languages])
  File &quot;/var/virtualenvs/livio/local/lib/python2.7/site-packages/django/db/models/manager.py&quot;, line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File &quot;/var/virtualenvs/livio/local/lib/python2.7/site-packages/django/db/models/query.py&quot;, line 450, in bulk_create
    self._batched_insert(objs_without_pk, fields, batch_size)
  File &quot;/var/virtualenvs/livio/local/lib/python2.7/site-packages/django/db/models/query.py&quot;, line 1056, in _batched_insert
    using=self.db)
  File &quot;/var/virtualenvs/livio/local/lib/python2.7/site-packages/django/db/models/manager.py&quot;, line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File &quot;/var/virtualenvs/livio/local/lib/python2.7/site-packages/django/db/models/query.py&quot;, line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File &quot;/var/virtualenvs/livio/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py&quot;, line 1060, in execute_sql
    cursor.execute(sql, params)
  File &quot;/var/virtualenvs/livio/local/lib/python2.7/site-packages/django/db/backends/utils.py&quot;, line 64, in execute
    return self.cursor.execute(sql, params)
  File &quot;/var/virtualenvs/livio/local/lib/python2.7/site-packages/django/db/utils.py&quot;, line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File &quot;/var/virtualenvs/livio/local/lib/python2.7/site-packages/django/db/backends/utils.py&quot;, line 64, in execute
    return self.cursor.execute(sql, params)
DataError: value too long for type character varying(5)

**Comment by yifili09** [comment]
@jemerick 
The commit of yifili09@14d995a just modify the [language accordingly] but failed on checking. 😿 😿 

image

**Pull request merged**
