### PR TITLE
Feature/Pixel density and scale

### PR DESCRIPTION
**Pull request by KhrystynaDubovyk**
Provides the information for #[2319](https://github.com/smartdevicelink/sdl_core/issues/2319)

This PR is **[ready]** for review.

### Summary
Update Structs index with new params for VideoStreamingCapabilities struct

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by IGapchuk** [comment]
NOTE: feature branch has been rebased onto current develop

**Comment by IGapchuk** [comment]
@kshala-ford Please, be informed that feature branch has been rebased onto current develop. Feel free to approve it, or suggest required changes.

**Comment by AStasiuk** [comment]
@kshala-ford other reviewers were removed.

**Comment by AStasiuk** [comment]
@theresalech, this PR is already reviewed and approved by Ford (by @kshala-ford) and ready for Livio review.

**Comment by IGapchuk** [comment]
@kshala-ford @JackLivio  Please be informed, that feature branch has been updated by a new commit (c01289ebe652a0e8571a7ebd8e6b2dbd9b7fd221) that adds changes according to the revision smartdevicelink/sdl_evolution#805

**Pull request merged**
