### PR TITLE
Add keyboard staff to set global properties

### PR DESCRIPTION
**Pull request by DrachenkoAnastasiia**
Added Description, table and new param autoCompleteList.

### CODE REVIEW

**Comment by DrachenkoAnastasiia** [comment]
please review
@KhrystynaDubovyk 
@tmelnyk

**Comment by DrachenkoAnastasiia** [comment]
please review @olesiav, @mghiumiusliu

**Comment by TMelnyk** [comment]
**Add keyboard staff** to set global properties
And the whole PR is regarding VRHelpTitle and VRHelp

Please re-work
+ please do NOT add such big texts in PRs
Introdusction and Motivation should be shortly
And why do you copy "HMI must"? We implemented SDL code and NOT HMI
Please remove ALL related to HMI behavior - it`s not our scope of work

**Comment by DrachenkoAnastasiia** [comment]
Guidelines consists the info regarding behavior only HMI. I could not remove it. 
Sections in Guidelines have not Introduction and Motivation.  
VRHelpTitle and VRHelp params were added previously, I added info regarding new one within updating all Section

**Comment by TMelnyk** [comment]
Oh, apologize 
I thought that it also just a PR for SDL Evol
Please ignore my prevous comment

**Comment by TMelnyk** [comment]
And why you didn`t create Review Notes at Jira as was requested?

**Comment by DrachenkoAnastasiia** [comment]
Today I`ll do it)

**Pull request merged**
