### PR TITLE
Add diagrams. Update the "note" with info about new behavior.

### PR DESCRIPTION
**Pull request by KhrystynaDubovyk**
Added diagrams. Updated the "note" with info about new behavior.

### CODE REVIEW

**Comment by mghiumiusliu** [comment]
Reviewed.

**Comment by pestOO** [comment]
@KhrystynaDubovyk,
Please, change destination branch - it shall be `develop` (if customer do not insist it's hotfix).

**Comment by KhrystynaDubovyk** [comment]
@mghiumiusliu, please approve that this pull request should be merged to master.

**Comment by jacobkeeler** [comment]
Closing as outdated

**Pull request closed without merging**
